#######################   Parameters Reference   #############################

                    #->> THIS IS OUTDATED <<--#

[[plap_group]]
# You can define multiple [[plap_group]] with each having distinct settings.

### CUSTOM SFX FOLDER NAMES ###################################################
# The name of the SFX folders containing your pistons/moans/etc items.
plap_folder_names = ["Plap1", "Plap2", "Plap3", "Plap4"]

###############################################################################

### REQUIRED ##################################################################
# This is the path to the interpolable to use as reference for the sfx.
# Make sure you Right Click->Rename it first before exporting to single file,
# or else it won't have a readable alias for this program.

# If the interpolable is not part of a group: "Name You Gave The Interpolable"

#Exemple: Your interpolable "Pos Waist" is part of a group(s), and the reference
#	      keyframe is at 00:02.454
# __________
#|  Main    |
#------------
# |   male   |      "00:02.454"
# ------------      ⇓
#  |Pos Waist|    ◆◆◆ ◆◆◆ ◆◆◆       ◆◆ ◆◆ ◆◆◆◆◆◆
#   ---------
interpolable_path = "main.B Rotation (cf_j_waist02)"

# Choose a keyframe where the subject is fully inserted
ref_keyframe_time = "00:00.000"

###############################################################################

### CUSTOMIZATION #############################################################
# Offset in seconds, in case you don't want the sfx to be timed exactly with 
# the reference keyframes. Can be positive or negative.
offset = 0.0

# Minimum percent distance (0.0 to 1.0) the subject needs to pull away from the
# contact point before re-enabling plaps.
# Prevents spam if the subject is making micro moves when fully inserted.
min_pull_out = 0.80

# Minimum percent distance (0.0 to 1.0) the subject needs to push toward the 
# contact point for a plap to register.
# This is in case the contact point gets closer and the subject does not need
# thrust as far.
min_push_in = 0.80

# By default sfx starts at 00:00.00000 and continue to the end.
# You can have a different start point, end point or multiple.
# Exemple with 2 ranges: [["00:01.5", "00:05.0"], ["00:10.5", "00:15.0"]]
# If you give a custom range, you must put both a Start and Stop point.
time_ranges = []

# V pattern goes from first folder to last to first repetively (1-2-3-4-3-2-1)
# W pattern is first -> last -> halway to first -> last -> first
# \ patern is first to last repetively
# A is opposite of V
# M is opposite of W
# / is opposite of \
# You can give multiple characters to vary the pattern, like "VW/\"
pattern_string = "V"

###############################################################################

# [In Development] Use it with Pregnancy+ or others

