[[plap_group]]
plap_folder_names = [ "Plap1", "Plap2", "Plap3", "Plap4",]
interpolable_path = "GO Position (cf_t_hips(work))"
ref_keyframe_time = "00:00.1610699"
offset = 0.0
min_pull_out = 0.81
min_push_in = 0.81
time_ranges = []
pattern_string = "W"

